# Generated by Django 5.1.7 on 2025-03-14 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BookRecords',
            fields=[
                ('id', models.IntegerField(blank=True, db_column='ID', primary_key=True, serialize=False)),
                ('date', models.TextField(blank=True, db_column='Date', null=True)),
                ('book_type', models.TextField(blank=True, db_column='BOOK TYPE', null=True)),
                ('date_ordered', models.TextField(blank=True, db_column='DATE ORDERED', null=True)),
                ('qty_ordered', models.IntegerField(blank=True, db_column='QTY ORDERED', null=True)),
                ('qty_received', models.FloatField(blank=True, db_column='QTY RECEIVED', null=True)),
                ('date_received', models.FloatField(blank=True, db_column='DATE RECEIVED', null=True)),
                ('agency_ordered_from', models.TextField(blank=True, db_column='AGENCY ORDERED FROM', null=True)),
                ('email', models.TextField(blank=True, db_column='EMAIL', null=True)),
                ('attachment', models.IntegerField(blank=True, db_column='ATTACHMENT', null=True)),
                ('status_of_order', models.TextField(blank=True, db_column='STATUS OF ORDER', null=True)),
                ('status_date', models.TextField(blank=True, db_column='STATUS DATE', null=True)),
            ],
            options={
                'db_table': 'book_records',
                'managed': False,
            },
        ),
    ]
