# Generated by Django 5.1.7 on 2025-03-14 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='can_register_user',
            field=models.BooleanField(default=False),
        ),
    ]
