# Generated by Django 5.1.7 on 2025-03-14 12:02

import affidavits.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Affidavits',
            fields=[
                ('id', models.IntegerField(blank=True, db_column='ID', primary_key=True, serialize=False)),
                ('date_received', models.TextField(blank=True, db_column='DATE RECEIVED', null=True)),
                ('date_required', models.TextField(blank=True, db_column='DATE REQUIRED', null=True)),
                ('officer_name', models.TextField(blank=True, db_column='OFFICER NAME', null=True)),
                ('contact_number', models.TextField(blank=True, db_column='CONTACT NUMBER', null=True)),
                ('licence_name', models.TextField(blank=True, db_column='LICENCE NAME', null=True)),
                ('dob', models.TextField(blank=True, db_column='DOB', null=True)),
                ('adress', models.TextField(blank=True, db_column='ADRESS', null=True)),
                ('vehicle_number', models.TextField(blank=True, db_column='VEHICLE NUMBER', null=True)),
                ('vehicle_owner', models.TextField(blank=True, db_column='VEHICLE OWNER', null=True)),
                ('mand', models.TextField(blank=True, db_column='MAND', null=True)),
                ('colour', models.TextField(blank=True, db_column='COLOUR', null=True)),
                ('chassis_number', models.TextField(blank=True, db_column='CHASSIS NUMBER', null=True)),
                ('engine_number', models.TextField(blank=True, db_column='ENGINE NUMBER', null=True)),
                ('status', models.TextField(blank=True, db_column='STATUS', null=True)),
                ('status_date', models.TextField(blank=True, db_column='STATUS DATE', null=True)),
                ('comments', models.TextField(blank=True, db_column='COMMENTS', null=True)),
                ('licence_number', models.TextField(blank=True, db_column='LICENCE NUMBER', null=True)),
                ('attachment', models.IntegerField(blank=True, db_column='ATTACHMENT', null=True)),
                ('type_requested', models.IntegerField(blank=True, db_column='TYPE REQUESTED', null=True)),
            ],
            options={
                'db_table': 'affidavits',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='RequestType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='AffidavitNew',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('affidavit_id', models.CharField(default=affidavits.models.generate_short_id, editable=False, max_length=8, unique=True)),
                ('date_received', models.DateField()),
                ('date_required', models.DateField()),
                ('officer_name', models.CharField(max_length=255)),
                ('contact_number', models.CharField(max_length=255)),
                ('licence_name', models.CharField(blank=True, max_length=255)),
                ('licence_number', models.CharField(blank=True, max_length=255, verbose_name='maker')),
                ('dob', models.DateField(blank=True)),
                ('address', models.TextField()),
                ('vehicle_owner', models.CharField(blank=True, max_length=255)),
                ('vehicle_number', models.CharField(blank=True, max_length=255)),
                ('maker', models.CharField(blank=True, max_length=255, verbose_name='maker')),
                ('chassis_number', models.CharField(blank=True, max_length=255, verbose_name='maker')),
                ('engine_number', models.CharField(blank=True, max_length=255, verbose_name='maker')),
                ('colour', models.CharField(blank=True, max_length=255, verbose_name='maker')),
                ('comments', models.TextField(blank=True)),
                ('attachment', models.FileField(blank=True, upload_to='affidavit_new/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='affidavit_new_created_by', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='affidavit_new_updated_by', to=settings.AUTH_USER_MODEL)),
                ('type_requested', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='affidavit_new', to='affidavits.requesttype')),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField()),
                ('comments', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('affidavit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='affidavit_comments', to='affidavits.affidavitnew')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='affidavit_created_by', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='affidavit_updated_by', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=255)),
                ('date', models.DateField()),
                ('comments', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('affidavit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='statuses', to='affidavits.affidavitnew')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_created_by', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_updated_by', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
