# Generated by Django 5.1.7 on 2025-03-14 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('affidavits', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='affidavitnew',
            name='dob',
            field=models.DateField(blank=True, verbose_name='D.O.B'),
        ),
    ]
