# Generated by Django 5.1.7 on 2025-03-14 16:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('affidavits', '0002_alter_affidavitnew_dob'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='affidavitnew',
            name='type_requested',
        ),
        migrations.AddField(
            model_name='affidavitnew',
            name='request_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='affidavit_request_types', to='affidavits.requesttype'),
        ),
    ]
