# Generated by Django 5.1.7 on 2025-03-14 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('affidavits', '0003_remove_affidavitnew_type_requested_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requesttype',
            name='name',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
