# Generated by Django 5.1.7 on 2025-03-14 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('affidavits', '0004_alter_requesttype_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='comment',
        ),
        migrations.AlterField(
            model_name='comment',
            name='comments',
            field=models.TextField(),
        ),
    ]
