# Generated by Django 5.1.7 on 2025-03-14 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('affidavits', '0005_remove_comment_comment_alter_comment_comments'),
    ]

    operations = [
        migrations.AddField(
            model_name='affidavitnew',
            name='slug',
            field=models.SlugField(blank=True, max_length=255, null=True, unique=True),
        ),
    ]
