# Generated by Django 5.1.7 on 2025-03-14 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('affidavits', '0006_affidavitnew_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='affidavitnew',
            name='chassis_number',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='affidavitnew',
            name='colour',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='affidavitnew',
            name='engine_number',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='affidavitnew',
            name='licence_number',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='affidavitnew',
            name='maker',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
