# Generated by Django 5.1.7 on 2025-03-14 18:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('affidavits', '0007_alter_affidavitnew_chassis_number_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['-created_at']},
        ),
    ]
