# Generated by Django 5.1.7 on 2025-03-07 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Exemptions',
            fields=[
                ('id', models.IntegerField(blank=True, db_column='ID', primary_key=True, serialize=False)),
                ('name_of_applicant', models.TextField(blank=True, db_column='NAME OF APPLICANT', null=True)),
                ('date_received', models.TextField(blank=True, db_column='DATE RECEIVED', null=True)),
                ('type_of_exemption', models.TextField(blank=True, db_column='TYPE OF EXEMPTION', null=True)),
                ('telephone_no_1', models.TextField(blank=True, db_column='TELEPHONE NO 1', null=True)),
                ('telephone_no_2', models.TextField(blank=True, db_column='TELEPHONE NO 2', null=True)),
                ('email', models.TextField(blank=True, db_column='EMAIL', null=True)),
                ('amount_to_be_paid', models.FloatField(blank=True, db_column='AMOUNT TO BE PAID', null=True)),
                ('status_1', models.TextField(blank=True, db_column='STATUS 1', null=True)),
                ('comments', models.TextField(blank=True, db_column='COMMENTS', null=True)),
                ('date_of_status_update', models.TextField(blank=True, db_column='DATE  OF STATUS UPDATE', null=True)),
                ('notes', models.TextField(blank=True, db_column='NOTES', null=True)),
                ('decision', models.TextField(blank=True, db_column='DECISION', null=True)),
                ('attachment', models.IntegerField(blank=True, db_column='ATTACHMENT', null=True)),
                ('status_2', models.TextField(blank=True, db_column='STATUS 2', null=True)),
                ('castries', models.IntegerField(blank=True, db_column='CASTRIES', null=True)),
                ('vieux_fort', models.IntegerField(blank=True, db_column='VIEUX FORT', null=True)),
            ],
            options={
                'db_table': 'exemptions',
                'ordering': ['-date_received'],
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='HPlates',
            fields=[
                ('id', models.IntegerField(blank=True, db_column='ID', primary_key=True, serialize=False)),
                ('date_received', models.TextField(blank=True, db_column='DATE RECEIVED', null=True)),
                ('applicant_s_name', models.TextField(blank=True, db_column="APPLICANT'S NAME", null=True)),
                ('primary_contact_number', models.FloatField(blank=True, db_column='PRIMARY CONTACT NUMBER', null=True)),
                ('registration_number', models.TextField(blank=True, db_column='REGISTRATION NUMBER', null=True)),
                ('vehicle_model_man', models.TextField(blank=True, db_column='VEHICLE  MODEL/ MAN', null=True)),
                ('chassis_vin_number', models.TextField(blank=True, db_column='CHASSIS VIN NUMBER', null=True)),
                ('action_taken', models.TextField(blank=True, db_column='ACTION TAKEN', null=True)),
                ('date', models.TextField(blank=True, db_column='DATE', null=True)),
                ('status', models.TextField(blank=True, db_column='STATUS', null=True)),
                ('attachments', models.IntegerField(blank=True, db_column='ATTACHMENTS', null=True)),
                ('new_aplication', models.IntegerField(blank=True, db_column='NEW APLICATION', null=True)),
                ('secondary_contact', models.TextField(blank=True, db_column='SECONDARY  CONTACT', null=True)),
                ('continued_use', models.IntegerField(blank=True, db_column='CONTINUED USE', null=True)),
            ],
            options={
                'db_table': 'hplates',
                'ordering': ['date_received'],
                'managed': False,
            },
        ),
    ]
